services:

  backend:
    build: backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - CORS_ORIGIN=http://localhost:3000
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - JWT_VALID_AUDIENCE=${JWT_VALID_AUDIENCE}
      - JWT_VALID_ISSUER=${JWT_VALID_ISSUER}

  frontend:
    restart: always
    build:
      context: frontend
      target: builder
    ports:
      - 3000:3000

  db:
    image: postgres
    hostname: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432

  # todo disable this when starting a productionish environment
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
volumes:
  db-data:
