services:
  backend:
    build:
      context: backend
      target: devtest
    restart: always
    networks:
      - app-network
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - CORS_ORIGIN=http://localhost:3000
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - JWT_VALID_AUDIENCE=${JWT_VALID_AUDIENCE}
      - JWT_VALID_ISSUER=${JWT_VALID_ISSUER}

  frontend:
    build: frontend
    restart: always
    networks:
      - app-network
    ports:
      - 443:443
    volumes:
      - ${CERT_DIRECTORY}:/etc/nginx/certs

  db:
    image: postgres
    hostname: postgres
    restart: always
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data
      - ${SQL_INIT_DIRECTORY}/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  app-network:


volumes:
  db-data:
  pgadmin-data:
