services:
  backend:
    image: digivisioacr.azurecr.io/digivisio-backend:latest
    restart: always
    networks:
      - app-network
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  frontend:
    image: digivisioacr.azurecr.io/digivisio-frontend:latest
    restart: always
    networks:
      - app-network
    ports:
      - 443:443
    volumes:
      - <somefolderhere>:/etc/nginx/certs

  db:
    image: postgres
    hostname: postgres
    restart: always
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432

networks:
  app-network:

volumes:
  db-data:
