name: digivisio

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # todo figure out if we want a separate layer for testing
      # - name: Build docker test image
      #   working-directory: backend
      #   run: docker build -t digivisio . --target test

      # - name: Run backend tests
      #   working-directory: backend
      #   run: docker run -e CI=true digivisio npm test

      # consider putting these in separate jobs
      # - name: Run frontend tests
      #   working-directory: backend
      #   run: docker run -e CI=true digivisio npm test

      - name: Build docker test image
        working-directory: backend
        run: docker build -t digivisio . --target prod

      - name: Run backend tests
        working-directory: backend
        run: docker run -e CI=true digivisio npm run test:ci

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [test, build]
  #   steps:
  #     - name: Deploy?!
  #       run: |
  #        # deploy somewhere
